name: CI
on:
  push: { branches: [master] }
  pull_request:
  workflow_call:
permissions: { contents: read }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: &CHECKOUT actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: &MISE jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
      - run: run -sk fmt-check test-locked lint lint-wasm
      - run: run wasm
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with: { name: plugin, path: "plugin.wasm\nschema.json", if-no-files-found: error }

  e2e:
    needs: validate
    runs-on: ubuntu-latest
    env: { download_dir: artifact }
    steps:
      - uses: *CHECKOUT
      - uses: *MISE
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with: { name: plugin, path: "${{ env.download_dir }}" }
      - env: { WASM_PATH: "${{ env.download_dir }}/plugin.wasm" }
        run: run -sk deno:scripts e2e release-notes
